dataset:
  observation_fieldnames:
    #  - index
    #  - sentence
    #  - lemma_sentence
    #  - upos_sentence
    #  - xpos_sentence
    #  - morph
    #  - head_indices
    #  - governance_relations
    #  - secondary_relations
     - length_matrix
     - embeddings
  adj_matrix: example/data/adjcora.npy
  embeddings: example/data/xcora.npy
  batch_size: 1
model:
  hidden_dim: 1024 # ELMo hidden dim
  #embedding_dim: 1024 # ELMo word embedding dim
  model_type: Graph-disk # BERT-disk, ELMo-disk, 
  use_disk: True
  model_layer: 2 # BERT-base: {1,...,12}; ELMo: {1,2,3}
probe:
  task_signature: word_pair # word, word_pair
  task_name: parse-distance
  maximum_rank: 32
  psd_parameters: True
  diagonal: False
  params_path: predictor.params
probe_training:
  epochs: 30
  loss: L1
reporting:
  root: example/results
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
    - spearmanr
      #- image_examples
    - uuas
